### ISSUE TITLE
How do I get this to work in check_mk (OMD) version 1.2?

### ISSUE THREAD

**Issue by greavette** [minodudd/check_mk-plugins#3]
Hi,

Thanks for writing up this plugin for nut.  I realize that this plugin is probably out of date with the new 1.2 version of check_mk I'm using today but I'm hoping you can point me in the right direction on getting this working.

I've installed NUT on my Raspberry Pi.  I've installed the check_mk agent on my Raspberry Pi.  I've taken your bash script and put on my Pi in /usr/lib/check_mk_agent/local.  I've made the script executable and confirmed that it gives me details from my connected UPS like your blog shows.

Now here comes the hard part.  I've then taken your python script and put it on my OMD/check_mk server in ~/local/share/check_mk.  I've made sure this python script is executable.

I then went into my check_mk and did a diagnosis of my Pi Host and in the test for the check_mk agent dump I can see all the wonderful NUT details.  Seems to be working in that test!

But when I go to services for that Pi Hosts in check_mk I see none of the NUT services listed?  

Is the Python script you wrote too old now to work with this version of check_mk?  Have I done something wrong in my implementation of your script?  Perhaps I need to re-write the bash script that runs on the Pi to provide the local checks needed by check_mk for the 4 columns of data it is looking for?

Any advice you can provide would be greatly appreciated.

**Comment by minodudd** [comment]
yeah, I'm afraid it might be too old. I've recently moved and don't have my check_mk set up yet (might take me a couple months to get it), so I can't even tell you the version I've last used it on.

The bash is simply there to dump the nut output to the agent output, so that doesn't sound like the problem.

It's most probably the python script acting up.

Sorry I can't be  more specific.

**Comment by greavette** [comment]
No worries.  Thank you for the reply.
